name = "Chumjar MC Server Modpack"
author = "memchk"
version = "1.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "504ed293a1ecd406025ba1c0e365540ca5dfa069c5a00a767c988f2ea3c4ba99"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
